site_name: LightKube
theme:
  name: material
  hljs_style: monokai
  palette:
    primary: deep purple

repo_name: gtsystem/lightkube
repo_url: https://github.com/gtsystem/lightkube
edit_uri: ""

nav:
  - QuickStart: index.md
  - Interface: client.md

markdown_extensions:
  - admonition
  - mkautodoc
  - codehilite
  - markdown_include.include:
      base_path: .
